services:
  - type: web
    name: career-compass-web
    runtime: static
    buildCommand: "npm ci && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://career-compass-api-wpgn.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
